DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
    User_ID SERIAL PRIMARY KEY,
    Username VARCHAR(256) NOT NULL,
    Password VARCHAR(256) NOT NULL,
    Salt VARCHAR(255) NOT NULL
);
