DROP TABLE IF EXISTS UserProfiles;
DROP TABLE IF EXISTS UserTokens;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
    User_ID SERIAL PRIMARY KEY,
    Username VARCHAR(256) UNIQUE NOT NULL,
    Password VARCHAR(256) NOT NULL,
    Salt VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserProfiles (
    Profile_ID SERIAL PRIMARY KEY,
    Email VARCHAR(256),
    FavoriteGenre VARCHAR(256),
    Profile_User_ID INT NOT NULL,
    FOREIGN KEY (Profile_User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);

CREATE TABLE UserTokens (
    Token VARCHAR(255) PRIMARY KEY,
    User_ID INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);

CREATE INDEX idx_tokens_token ON UserTokens(token);
CREATE INDEX idx_tokens_user_id ON UserTokens(user_id);
