DROP TABLE IF EXISTS UserProfiles;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
    User_ID SERIAL PRIMARY KEY,
    Username VARCHAR(256) NOT NULL,
    Password VARCHAR(256) NOT NULL,
    Salt VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserProfiles (
    Profile_ID SERIAL PRIMARY KEY,
    Email VARCHAR(256),
    FavouriteGenre VARCHAR(256),
    Profile_User_ID INT NOT NULL,
    FOREIGN KEY (Profile_User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
)
